In [2]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:", temperatures_w1)

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [3]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


In [4]:
temperatures_f = (temperatures_w1 * 9 / 5) + 32
print("Temperatures in Fahrenheit:", temperatures_f)

print("Maximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [5]:
first_three_days = temperatures_w1[:3]

weekend = temperatures_w1[-2:]

middle_three_days = temperatures_w1[2:5]

print("First three days:", first_three_days)
print("Weekend:", weekend)
print("Middle three days:", middle_three_days)

First three days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]


In [6]:
temperatures = np.array(
    [
        [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Row 1: Week 1
        [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1],  # Row 2: Week 2
    ]
)

print("2D Array:\n", temperatures)

2D Array:
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [7]:
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

print("\nWeek 1 temperatures:", temperatures[0, :])
print("Week 2 temperatures:", temperatures[1, :])

print("\nWeekend temperatures (both weeks):\n", temperatures[:, -2:])

Shape: (2, 7)
Data type: float64
Total number of elements: 14

Week 1 temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekend temperatures (both weeks):
 [[24.8 21.9]
 [22.8 20.1]]


In [8]:
import pandas as pd

marks_data = [95, 92, 89, 85, 80]
ranks = ["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]

marks = pd.Series(data=marks_data, index=ranks)
print("Marks Series:\n", marks)

Marks Series:
 Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [9]:
print("1st Rank Mark (position 0):", marks.iloc[0])

print("\nTop 3 Ranks (.loc):\n", marks.loc["Rank1":"Rank3"])

print("\n3rd Rank Mark (.iloc):", marks.iloc[2])

print("\nRanks with marks > 90:\n", marks[marks > 90])

1st Rank Mark (position 0): 95

Top 3 Ranks (.loc):
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd Rank Mark (.iloc): 89

Ranks with marks > 90:
 Rank1    95
Rank2    92
dtype: int64


In [10]:
marks["Rank1"] = 100

marks = marks.drop("Rank5")

print("Updated Series after modification and drop:\n", marks)

cgpa = marks / 10
print("\nCGPA Series:\n", cgpa)

Updated Series after modification and drop:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA Series:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [13]:
import pandas as pd

data = {
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": [
        "Electronics",
        "Clothing",
        "Electronics",
        "Furniture",
        "Clothing",
        "Electronics",
        "Furniture",
        "Clothing",
        "Furniture",
        "Electronics",
    ],
    "Region": [
        "North",
        "South",
        "North",
        "East",
        "West",
        "North",
        "East",
        "West",
        "South",
        "North",
    ],
    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400],
}

transactions = pd.DataFrame(data)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [14]:
print("Head (First 5 rows):\n", transactions.head())
print("\nTail (Last 5 rows):\n", transactions.tail())
print("\nShape:", transactions.shape)
print("Column Names:", list(transactions.columns))
print("\nData Types:\n", transactions.dtypes)

print(
    "\nSelected Columns:\n", transactions[["ProductCategory", "Amount"]]
)

print("\nLast 3 Columns:\n", transactions.iloc[:, -3:])

filtered_df = transactions[
    (transactions["Region"] == "North") & (transactions["Amount"] > 200)
]
print("\nFiltered (Region == 'North' & Amount > 200):\n", filtered_df)

print(
    "\nProductCategory Value Counts:\n",
    transactions["ProductCategory"].value_counts(),
)

print("\nUnique Regions:", transactions["Region"].unique())

print(
    "\nMean Amount by Region:\n",
    transactions.groupby("Region")["Amount"].mean(),
)

Head (First 5 rows):
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail (Last 5 rows):
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)
Column Names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']

Data Types:
 TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

Selected Columns:
   ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothi

In [15]:
transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165

transactions["Discount"] = transactions["Amount"] * 0.10
print("After updating ID 102 and adding Discount:\n", transactions)

transactions = transactions[transactions["TransactionID"] != 109]

transactions = transactions.drop(columns=["Discount"])

print(
    "\nFinal DataFrame (ID 109 removed & Discount deleted):\n", transactions
)

After updating ID 102 and adding Discount:
    TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

Final DataFrame (ID 109 removed & Discount deleted):
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105       